name: bigdata
channels:
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=39.0.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - flit-core=3.8.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - idna=3.4
  - importlib_resources=5.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.2
  - jupyter_core=5.2.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=3.0.5
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.6
  - notebook-shim=0.2.2
  - openssl=1.1.1t
  - packaging=23.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.36
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - qtwebkit=5.212
  - requests=2.28.1
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.1
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - typing_extensions=4.4.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - anyio==3.6.2
      - arrow==1.2.3
      - asttokens==2.2.1
      - attrs==22.2.0
      - backports-zoneinfo==0.2.1
      - bcrypt==4.0.1
      - beautifulsoup4==4.11.2
      - bleach==6.0.0
      - blosc2==2.0.0
      - bokeh==2.4.3
      - click==8.1.3
      - cloudpickle==2.2.1
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.35
      - dash==2.10.0
      - dash-bootstrap-components==1.4.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dask==2023.3.1
      - dask-jobqueue==0.8.1
      - debugpy==1.6.6
      - distributed==2023.3.1
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - flask==2.2.3
      - fonttools==4.39.2
      - fqdn==1.5.1
      - fsspec==2023.3.0
      - greenlet==2.0.2
      - h5py==3.8.0
      - heapdict==1.0.1
      - importlib-metadata==6.1.0
      - importlib-resources==5.12.0
      - install==1.3.5
      - ipykernel==6.21.3
      - ipython==8.11.0
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jsonpointer==2.3
      - jupyter-client==8.0.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - kiwisolver==1.4.4
      - locket==1.0.0
      - lz4==4.3.2
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mistune==2.0.5
      - msgpack==1.0.5
      - nbclassic==0.5.3
      - nbclient==0.7.2
      - nbconvert==7.2.10
      - nbformat==5.7.3
      - notebook==6.5.3
      - numexpr==2.8.4
      - numpy==1.24.2
      - pandas==1.5.3
      - paramiko==3.2.0
      - partd==1.3.0
      - pillow==9.4.0
      - platformdirs==3.1.1
      - plotly==5.14.1
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.4
      - psycopg==3.1.8
      - psycopg2==2.9.5
      - py-cpuinfo==9.0.0
      - pyarrow==11.0.0
      - pygments==2.14.0
      - pynacl==1.5.0
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-box==7.0.1
      - python-json-logger==2.0.7
      - pytz==2022.7.1
      - pyyaml==6.0
      - pyzmq==25.0.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scp==0.14.5
      - seaborn==0.12.2
      - sniffio==1.3.0
      - sodapy==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4
      - sqlalchemy==2.0.7
      - stack-data==0.6.2
      - tables==3.8.0
      - tblib==1.7.0
      - tenacity==8.2.2
      - toolz==0.12.0
      - traitlets==5.9.0
      - typing-extensions==4.5.0
      - tzdata==2022.7
      - uri-template==1.2.0
      - urllib3==1.26.15
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - werkzeug==2.2.3
      - zict==2.2.0
      - zipp==3.15.0
