import dask.dataframe as dd

TABLE_NAME_PARKING_VIOLATION_ISSUED = 'PARKING_VIOLATION_ISSUED'

INCLUDED_COLUMNS_PARKING_VIOLATION_ISSUED = [
    'Summons Number',
    'Plate ID',
    'Registration State',
    'Plate Type',
    'Issue Date',
    'Violation Code',
    'Vehicle Body Type',
    'Vehicle Make',
    'Issuing Agency',
    'Street Code1',
    'Street Code2',
    'Street Code3',
    'Vehicle Expiration Date',
    'Violation Location',
    'Violation Precinct',
    'Issuer Precinct',
    'Issuer Code',
    'Issuer Command',
    'Issuer Squad',
    'Violation Time',
    'Time First Observed',
    'Violation County',
    'Violation In Front Of Or Opposite',
    'House Number',
    'Street Name',
    'Intersecting Street',
    'Date First Observed',
    'Law Section',
    'Sub Division',
    'Violation Legal Code',
    'Days Parking In Effect',
    'From Hours In Effect',
    'To Hours In Effect',
    'Vehicle Color',
    'Unregistered Vehicle?',
    'Vehicle Year',
    'Meter Number',
    'Feet From Curb',
    'Violation Post Code',
    'Violation Description',
    'No Standing or Stopping Violation',
    'Hydrant Violation',
    'Double Parking Violation'
]
DTYPES_PARKING_VIOLATION_ISSUED = {
    'Summons Number': 'float64',
    'Plate ID': 'str',
    'Registration State': 'str',
    'Plate Type': 'str',
    'Issue Date': 'str',
    'Violation Code': 'float64',
    'Vehicle Body Type': 'str',
    'Vehicle Make': 'str',
    'Issuing Agency': 'str',
    'Street Code1': 'float64',
    'Street Code2': 'float64',
    'Street Code3': 'float64',
    'Vehicle Expiration Date': 'str',
    'Violation Location': 'str',
    'Violation Precinct': 'float64',
    'Issuer Precinct': 'float64',
    'Issuer Code': 'float64',
    'Issuer Command': 'str',
    'Issuer Squad': 'str',
    'Violation Time': 'str',
    'Time First Observed': 'str',
    'Violation County': 'str',
    'Violation In Front Of Or Opposite': 'str',
    'House Number': 'str',
    'Street Name': 'str',
    'Intersecting Street': 'str',
    'Date First Observed': 'str',
    'Law Section': 'str',
    'Sub Division': 'str',
    'Violation Legal Code': 'str',
    'Days Parking In Effect': 'str',
    'From Hours In Effect': 'str',
    'To Hours In Effect': 'str',
    'Vehicle Color': 'str',
    'Unregistered Vehicle?': 'str',
    'Vehicle Year': 'float64',  # Added to handle NA values
    'Meter Number': 'str',
    'Feet From Curb': 'float64',
    'Violation Post Code': 'str',
    'Violation Description': 'str',
    'No Standing or Stopping Violation': 'str',
    'Hydrant Violation': 'str',
    'Double Parking Violation': 'str',
    'Number': 'str',
    'Street': 'str',
    'Days Parking In Effect    ': 'str'

}


def rename_PVI(data: dd.DataFrame):
    return data.rename(columns={
        'Number': 'House Number',
        'Street': 'Street Name',
        'Days Parking In Effect    ': 'Days Parking In Effect'
    })