cluster:
  local:
    n_workers: 2
    threads_per_worker: 4
  hpc:
    memory: 16GB
    cores: 16
    processes: 4
    jobs: 4

environment:
  local:
    data_augmentation_dir: data/csv/augmentation
    data_original_dir: data/csv/original_old
    data_output_dir: data
  hpc:
    data_augmentation_dir: /d/hpc/home/lz3057/data/augmentation
    data_original_dir: /d/hpc/projects/FRI/bigdata/data/NYTickets
    data_output_dir: /d/hpc/home/lz3057/data/processed