TABLE_NAME_EVENT = f'EVENT'

INCLUDED_COLUMNS_EVENT = [
    'event_id',
    'title',
    'date',
    'start_time',
    'end_time',
    'location_description',
    'description',
    'snippet',
    'phone',
    'email',
    'cost_free',
    'cost_description',
    'must_see',
    'url',
    'notice',
    'event_id_location',
    'name',
    'park_id',
    'lat',
    'long',
    'address',
    'zip',
    'borough',
    'accessible'
]
DTYPES_EVENT = {
    'event_id': 'str',
    'title': 'str',
    'date': 'str',
    'start_time': 'str',
    'end_time': 'str',
    'location_description': 'str',
    'description': 'str',
    'snippet': 'str',
    'phone': 'str',
    'email': 'str',
    'cost_free': 'float64',
    'cost_description': 'str',
    'must_see': 'str',
    'url': 'str',
    'notice': 'str',
    'event_id_location': 'str',
    'name': 'str',
    'park_id': 'str',
    'lat': 'float64',
    'long': 'float64',
    'address': 'str',
    'zip': 'float64',
    'borough': 'str',
    'accessible': 'float64'
}
