TABLE_NAME_SCHOOLS = f'SCHOOLS'

INCLUDED_COLUMNS_SCHOOLS = [
    'Police Precinct',
    'Number of Schools',
]
DTYPES_SCHOOLS = {
    'fiscal_year': 'str',
    'system_code': 'str',
    'location_code': 'str',
    'location_name': 'str',
    'BEDS': 'str',
    'Managed_by_name': 'str',
    'location_type_description': 'str',
    'Location_Category_Description': 'str',
    'Grades_text': 'str',
    'Grades_final_text': 'str',
    'open_date': 'str',
    'Status_descriptions': 'str',
    'Primary_building_code': 'str',
    'primary_address_line_1': 'str',
    'State_code': 'str',
    'X_COORDINATE': 'str',
    'Y_COORDINATE': 'str',
    'LONGITUDE': 'str',
    'LATITUDE': 'str',
    'Community_district': 'str',
    'Council-district': 'str',
    'Census_tract': 'str',
    'Borough_block_lot': 'str',
    'NTA': 'str',
    'NTA_Name': 'str',
    'Principal_Name': 'str',
    'Principal_title': 'str',
    'Principal_phone_number': 'str',
    'fax_number': 'str',
    'Geographical_District_code': 'str',
    'Administrative_District_Code': 'str',
    'Administrative_District_Name': 'str',
    'community_school_sup_name': 'str',
    'Tier_3_Support_Location_Name': 'str',
    'Tier_3_Support_Leader_Name': 'str',
    'Tier_2_Support_Location_Name': 'str',
    'HighSchool_Network_Location_Code': 'str',
    'HighSchool_Network_Name': 'str',
    'HighSchool_Network_Superintendent': 'str',
    'Community_district 1': 'str',
    'Police_precinct': 'str',
}
